### ISSUE TITLE
Multiple watches?

### ISSUE THREAD

**Issue by mike-post** [ember-intl/ember-intl#188]
What is up with the multiple watches that are added to watchman?  I installed ember-intl (via `ember install ember-intl@2.0.0-beta.15`) and instantly had five (!!!) additional watches.  I'm using ember-cli 1.13.6.  Here's the output of `watchman watch-list`:

``` json
{
    "version": "3.3.0",
    "roots": [
        "/Users/username/projects/myapp/node_modules/ember-intl",
        "/Users/username/projects/myapp/node_modules/ember-intl/node_modules/ember-intl-format-cache",
        "/Users/username/projects/myapp/node_modules/ember-intl/node_modules/ember-intl-messageformat/node_modules/ember-intl-messageformat-parser",
        "/Users/username/projects/myapp/node_modules/ember-intl/node_modules/ember-intl-messageformat",
        "/Users/username/projects/myapp/node_modules/ember-intl/node_modules/ember-intl-relativeformat",
        "/Users/username/projects/myapp"
    ]
}
```

I'm also getting a ton of messages similar to this one:

```
Recrawled this watch 25 times, most recently because:
/Users/username/projects/myapp: kFSEventStreamEventFlagUserDropped
To resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
```

Using `ember serve` with the default live reload script, my app gets reloaded a minimum of two times (and sometimes more) when I change a single file. Manually deleting the watches with `watchman watch-del <path>` has no effect as they are all recreated upon the next `ember serve`.

**Comment by jasonmit** [comment]
Not entirely sure.  I haven't seen this yet, will not try to reproduce.  Is your app public?

**Comment by mike-post** [comment]
Alas, it is not.

**Comment by mike-post** [comment]
There's this issue https://github.com/ember-cli/ember-cli/issues/4101, but I suspect it's unrelated. I tried the workaround I came up with for that issue and it did not work. It's also interesting to note that the recrawl error lists 25 invocations, which is the number of watches added by ember-intl, squared.

Also, I'm running on io.js 2.5.0, but again, I think that's unrelated (since watchman is native code running outside of the node runtime).

**Comment by jasonmit** [comment]
> "roots": [
        "/Users/username/projects/myapp/node_modules/ember-intl",
        "/Users/username/projects/myapp/node_modules/ember-intl/node_modules/ember-intl-format-cache",
        "/Users/username/projects/myapp/node_modules/ember-intl/node_modules/ember-intl-messageformat/node_modules/ember-intl-messageformat-parser",
        "/Users/username/projects/myapp/node_modules/ember-intl/node_modules/ember-intl-messageformat",
        "/Users/username/projects/myapp/node_modules/ember-intl/node_modules/ember-intl-relativeformat",
        "/Users/username/projects/myapp"
    ]

These are just all the files on your filesystem with a `.watchmanconfig` nothing to be concerned with.

The recrawling is a separate issue, I'll try and reproduce.

**Comment by jasonmit** [comment]
Could you clone this repo and run it:
https://github.com/jasonmit/ember-intl-example

It's a very raw basic app updated with the latest deps.  See if you're able to reproduce this issue against that app.

**Comment by jasonmit** [comment]
https://facebook.github.io/watchman/docs/config.html#fsevents-latency have you attempted mutating this value in your watchman config?

**Comment by jasonmit** [comment]
I made some changes for beta.16 to hopefully address this but like I said, I am unable to validate.  At the least, it should remove the node_modules addons for ember-intl in `watchman watch-list` (be sure to clear it first via `watchman watch-del-all`)

**Comment by jasonmit** [comment]
Closing, appears to be fixed in watchman see ember-cli#4101.

**Comment by thedeeno** [comment]
I'm still experiencing this issue unfortunately. Adding ember-intl beta.16 to my `package.json` causes many rebuilds after writing a template file.

output of `watchman watch-list`
```
{
    "version": "3.6.0",
    "roots": [
        "/Users/dane/code/company/member-web"
    ]
}
```

For some extra diagnostics I ran `broccoli-duplicate-watched-tree-finder`

```
All watched trees:
  - /Users/dane/code/company/member-web/node_modules/ember-intl/node_modules/ember-intl-format-cache/node_modules/intl-format-cache/src
  - /Users/dane/code/company/member-web/node_modules/ember-intl/node_modules/ember-intl-messageformat/node_modules/ember-intl-messageformat-parser/node_modules/intl-messageformat-parser/src
  - /Users/dane/code/company/member-web/node_modules/ember-intl/node_modules/ember-intl-messageformat/node_modules/intl-messageformat/src
  - /Users/dane/code/company/member-web/node_modules/ember-intl/node_modules/ember-intl-relativeformat/node_modules/intl-relativeformat/src
  - /Users/dane/code/company/member-web/node_modules/ember-intl/node_modules/intl/dist
  - /Users/dane/code/company/member-web/node_modules/ember-intl/node_modules/intl/locale-data/jsonp
  - app
  - bower_components/chai
  - bower_components/ember
  - bower_components/ember-cli-shims
  - bower_components/ember-data
  - bower_components/ember-load-initializers
  - bower_components/ember-mocha
  - bower_components/ember-mocha-adapter
  - bower_components/ember-resolver/dist/modules
  - bower_components/ember-simple-auth
  - bower_components/jquery/dist
  - bower_components/loader.js
  - bower_components/mocha
  - bower_components/numeral
  - config
  - public
  - tests
  - translations
  - vendor
```

Notice how `ember-intl` is adding itself to the watched tree with absolute paths. Perhaps using `broccoli-unwatched-tree` as seen [here](https://github.com/sebastianseilund/broccoli-duplicate-watched-tree-finder) will help?

**Comment by thedeeno** [comment]
More information: I think the issue is coming from this addon's `treeForPublic` method. Commenting it out in my local fork resolves the issue.

Still looking...

**Comment by thedeeno** [comment]
Found it. The problem occurs when `intlOptions.locales` is undefined, thus the `include` filter for the local funnel never gets populated. I fixed it in my fork by setting a default for the include filter on ln 150.

`var include = [/en-US/i];`

I'm not familiar enough with this library to say if know if that's sensible, but it works. Let me know if there's any more info I can provide.

**Comment by jasonmit** [comment]
Okay, are you on OSX as well?  And the fix in ember-cli branch I pointed to above involving updating watchman to the latest devel doesn't fix it?

**Comment by thedeeno** [comment]
OSX, using watchman HEAD, ember-cli 1.13.6

**Comment by jasonmit** [comment]
If you know the locales you're targeting, you can specify them manually, which I assume will also make your recrawl go away.

https://github.com/yahoo/ember-intl#cherry-pick-cldr-modules

> OSX, using watchman HEAD, ember-cli 1.13.6

I still feel this is a watchman issue choking on the number of files being transferred.  Have you tried adjusting the fsevents latency?  https://github.com/ember-cli/ember-cli/issues/4101#issuecomment-126867860

**Comment by jasonmit** [comment]
Is this still an issue on beta.17?

**Comment by thedeeno** [comment]
I'll check it out this weekend

**Comment by jasonmit** [comment]
@thedeeno when you do, be sure to also pull in latest watchman.

**Comment by stefanpenner** [comment]
Try upgrading to watchman 3.7 it has a fix for this issue.

**Comment by jasonmit** [comment]
Please feel free to reply and I'll reopen, but it appears to be resolved AFAIK.

**Comment by thedeeno** [comment]
Will do. Still haven't had a chance to get back to this project yet. Thanks for following up!

**Comment by thedeeno** [comment]
Issue still persists in `watchman --HEAD (>3.8)` and `ember-intl-2.0.0-beta-23` :(

**Comment by phcoliveira** [comment]
I am using Watchman 4.6.0 and Ember 2.8.4. Although I run only one ember server, watchman is still watching all my Ember projects.

**Comment by jasonmit** [comment]
Reopening to investigate

**Comment by jasonmit** [comment]
@phcoliveira all your projects or all projects that include ember-intl?  I'm trying to determine if this is something isolated to ember-intl or ember-cli/watchman.

**Comment by phcoliveira** [comment]
It is likely to be isolated, for it was extremely difficult to find anything related to this problem. I created a new project today and, within a few file savings, had Watchman complaining about being poisoned. The files that could not be added was from another project. As a response to the command `watchman watch-list`, the list of folders being watched included the other projects. To circumvent this problem, I excluded the other folders using the command `watchman watch-del`.

I don't remember doing anything special when installing Watchman. Here it is my global config file.
``` JSON
{
  "enforce_root_files": true,
  "root_files": [".watchmanconfig"],
  "ignore_vcs": [],
  "ignore_dirs": [
    ".git",
    ".hg",
    ".svn",
    "build",
    "tmp",
    "temp",
    "log",
    "node",
    "node_modules",
    "dist",
    "bower_components",
    ".sass-cache"
  ]
}
```

**Comment by jasonmit** [comment]
https://github.com/ember-intl/ember-intl-relativeformat/commit/e0ff3631fff9fbe9e756f1f56dbded6c512e832e
https://github.com/ember-intl/ember-intl-messageformat-parser/commit/edeb38ee1a981f7e7013ff4707c8c6c5536fad3a
https://github.com/ember-intl/ember-intl-messageformat/commit/9d8382b105426f4aae046ace9fdbbfcbc6db14b6
https://github.com/ember-intl/ember-intl-format-cache/commit/44d8ea2b06df810ae7decb79874db6c935576442

Should be the fix for the issue - I just published patches for all 4.  Please reopen if you still see this.
